version: "3.8"
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - petdjango-db-data:/var/lib/postgresql/data/
  nginx:
    build: .\nginx
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - petdjango-static:/var/www/static
      - petdjango-media:/var/www/media
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8000"
    command: poetry run python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/logs:/var/www/src/logs
      - petdjango-static:/var/www/static
      - petdjango-media:/var/www/media
volumes:
  petdjango-static:
  petdjango-media:
  petdjango-db-data:
